[package]
name = "sigchld"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.172"
signal-hook = { version = "0.3.18", default-features = false }

[dev-dependencies]
anyhow = "1.0.98"
duct = "1.0.0"
